name: mobileorders
description: description app.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  ## State manager, dependens enjection
  provider: ^6.0.2
  ## State manager
  flutter_bloc: ^8.0.1
  ### DataBase
  moor_flutter: ^4.1.0 # (sql ORM)
  ## Локальное хранение маленьких данныых
  shared_preferences: ^2.0.7
  ## api
  dio: ^4.0.6
  http: ^0.13.3
  equatable: ^2.0.3
  # Either принимает два значения ошибка и результат
  dartz: ^0.10.0
  ## Firebase service for auth (Google)
  firebase_core: ^1.17.0
  firebase_auth_oauth: ^1.2.0
  firebase_auth: ^3.3.18 ###
  ### Заставка при прогрузки, чтобы не вылезали стремные артифакты
  shimmer: ^2.0.0
  ## Закгрузка URL изображения
  cached_network_image: ^3.1.0
  ## Закгрузка URL изображения с сжатием
  optimized_cached_image: ^3.0.0
  ## Для локализации текста в приложении
  # flutter_localizations:
  #   sdk: flutter
  # intl: ^0.17.0
  # flutter_localized_locales: ^2.0.1
  ## Нужно для того чтобы не было белого экрана на андроид
  flutter_native_splash: ^2.1.6
  ##date
  intl: ^0.17.0

  
## зорошо работает на Android но не на ios нужно удалять перед пелизам на ios
flutter_native_splash:
    image: icons/logo.png
    color: "587CC0"
    ios: false
    android_gravity: center
    # web_image_mode: center  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  ## Для генерации моделей и т.д. moor (sql ORM)
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.2
  ### Diagram UML for code нужен только при авто генерации UML из кода
  # dcdg: ^4.0.0
  
  ## Он всегда лежить в корневом каталоге в пользователе, потому что это debug ключ
  # keytool -list -v -keystore "C:\Users\k4fos\.android\debug.keystore" -alias androiddebugkey -storepass android -keypass android


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - icons/
    - images/
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
